---
title: "Ravens"
author: "Sam & Steve"
date: "Oct 11, 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,fig.width=5, fig.height=4,fig.align = "center",cache=TRUE)
```

```{r, include=FALSE, echo=FALSE}
library(rstan)
library(lme4)
library(ggplot2)
library(tidyr)
library(dplyr)
library(broom)
library(gridExtra)
library(patchwork)
library(latex2exp)
library(GGally) # for ggpairs 



paper_theme <- theme_classic() + theme( axis.title.x = element_text(size=18),
  axis.text.x=element_text(colour="black", 
                           size = 14), 
  axis.title.y = element_text(size = 18, vjust = 1),
  axis.text.y  = element_text(size = 14),
  strip.text=element_text(size=16),
  legend.title=element_text(size=18),
  title=element_text(size=14),
  legend.text=element_text(size=16))  

## ===============
## Data processing
## ===============

d <- read.csv("data.csv")
d$subject <- as.character(d$uniqueid) # make normally numbered

d <- subset(d, rt < 2*60*1000) # Toss big outliers
d$correct.fac <- as.factor(d$correct)

d <- d %>% 
	group_by(subject) %>%
	filter(median(rt) > 10000) %>%
	transform(rt.z=scale(rt)[,1]) %>%
	ungroup()

d$uniqueid <- droplevels(as.factor(d$uniqueid))
d$SubjectFrom1 <- as.numeric(d$uniqueid)

th <- theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))


```


```{r}

#############################################################
## Construct stan data and run
#############################################################

stan.data <- list(NROWS=nrow(d),
                  NSUBJ=max(d$SubjectFrom1),
                  NITEMS=max(d$which_item),
                  RTz=d$rt.z, ## NOT z-scored within subjects 
                  correct=d$correct,
                  subject=d$SubjectFrom1,
                  item=d$which_item)

# This is the part that actually runs stan:
fit <- stan(file="model.stan", data=stan.data, iter=50000, chains=2, cores=2)

#############################################################
## Extract
#############################################################

ex <- function(var,idx) { unlist(rstan::extract(fit, paste0(var,"[",idx,"]"), permuted=TRUE)) }
myq <- function(x) {     data.frame(y=mean(x), ymin=quantile(x,0.25), ymax=quantile(x,0.75)) }

# extract from fit: 
a <- NULL
for(i in 1:max(d$SubjectFrom1)) {
    sd <- subset(d,SubjectFrom1==i)
    
    a <- rbind(a,data.frame(SubjectFrom1=i
                            ,gamma0=ex("sgamma0",i)
                            ,gamma1=ex("sgamma1",i)
                            ,gamma2=ex("sgamma2",i)
                            ,sbeta0=ex("sbeta0",i)
                            ,sbeta1=ex("sbeta1",i)
                            ,threshold50=ex("threshold50",i)
                            ,timehardest50=ex("timehardest50", i)
                            ,correct=mean(sd$correct)
                            ,income=sd$income[1]
                            ,medianRT=median(sd$rt)
                            ))
}

# a, but medians:
am <- a %>% group_by(SubjectFrom1) %>% 
            summarise( gamma0=median(gamma0)
                      ,gamma1=median(gamma1)
                      ,gamma2=median(gamma2)
                      ,sbeta0=median(sbeta0)
                      ,sbeta1=median(sbeta1)
                      ,threshold50=median(threshold50)
                      ,timehardest50=median(timehardest50)
                      ,correct=mean(correct)) %>%
            ungroup()
        

```


```{r}
ggplot(a, aes(y=timehardest50, x=correct, group=SubjectFrom1)) + 
        aes(y=gamma0)+labs(x="Correct",y=TeX("$\\gamma_0 + \\gamma_{s0}$"))+ggtitle("Accuracy Intercept") +

        stat_summary(fun = median, geom = "point", alpha=0.3) + 
        stat_summary(fun.data = myq, geom = "errorbar", width=0.005, alpha=0.2) + 
        geom_hline(yintercept=0, color="black", alpha=0.5,linetype="dotted") +
        paper_theme



 ggplot(regp) + 
            geom_histogram(aes(x=rtIcptEffect,fill="l1"), binwidth=0.05,alpha=0.8) + 
            geom_histogram(aes(x=rtSlopeEffect,fill="l2"),binwidth=0.05,alpha=0.8) +
            geom_histogram(aes(x=rtInteraction,fill="l3"), binwidth=0.05,alpha=0.8)  +
          
            labs(x="Parameter estimates", y="Samples") +
            scale_fill_manual(values=c("gray","dodgerblue","orange"), labels=c(expression(lambda[1],lambda[2],lambda[3]))) +
            #labels=c(TeX("$\\lambda_1"),TeX("$\\lambda_2"),TeX("$\\lambda_3"))) +
            paper_theme + theme(legend.title=element_blank(), legend.position=c(0.9,0.85)) +
            coord_cartesian(xlim=c(-1.8,1.3))


```

```{r}

#############################################################
## Plot
#############################################################



## Plot the key coefficients vs. correctness
p <- ggplot(a, aes(y=timehardest50, x=correct, group=SubjectFrom1)) + 
        stat_summary(fun = median, geom = "point", alpha=0.3) + 
        stat_summary(fun.data = myq, geom = "errorbar", width=0.005, alpha=0.2) + 
        geom_hline(yintercept=0, color="black", linetype="dotted") +
        xlab("Mean accuracy") +
        paper_theme


regp <- data.frame(rtIcptEffect=rstan::extract(fit, "rtIcptEffect"),
                   rtSlopeEffect=rstan::extract(fit, "rtSlopeEffect"),
                   rtInteraction=rstan::extract(fit, "rtInteraction"))

pparam <-  ggplot(regp) + 
            geom_histogram(aes(x=rtIcptEffect,fill="l1"), binwidth=0.05,alpha=0.8) + 
            geom_histogram(aes(x=rtSlopeEffect,fill="l2"),binwidth=0.05,alpha=0.8) +
            geom_histogram(aes(x=rtInteraction,fill="l3"), binwidth=0.05,alpha=0.8)  +
          
            labs(x="Parameter estimates", y="Samples") +
            scale_fill_manual(values=c("gray","dodgerblue","orange"),
                              labels=c(expression(lambda[1],lambda[2],lambda[3]))) +
            paper_theme + theme(legend.title=element_blank(), legend.position=c(0.13,0.85)) +
            geom_vline(xintercept=0,linetype="dotted") +
            coord_cartesian(xlim=c(-1.45,1.9))


p+aes(y=gamma0)+ylab(TeX("$\\gamma_0 + \\gamma_{s0}$"))
p+aes(y=gamma1)+ylab(TeX("$\\gamma_1 + \\gamma_{s1}$"))
p+aes(y=gamma2)+ylab(TeX("$\\gamma_2 + \\gamma_{s2}$"))
p+aes(y=sbeta0)+ylab(TeX("$\\beta_0 + \\beta_{s1}$"))
p+aes(y=sbeta1)+ylab(TeX("$\\beta_1 + \\beta_{s1}$"))
pparam

```
	  
